-- VERB LIST
verb = {"attack", "get in a switchblade fight with", "swallow", "hug", "snuggle", "gently pat", "flick", "chew", "chomp", "put on golf cleats and jump on", "contradict", "get in a very loud argument with", "make love to", "put my dick into", "shove my cock into", "force my fist into", "deepfry", "grow old with", "get married to", "spend months going through legal processes to adopt", "confuse", "rape", "kill", "mame", "destory", "descimate", "cum on", "jizz on", "ejaculate all over", "be the last man in a 100 man bukake involving", "eat raw then shit out", "race around the world while carrying", "beat up", "clone", "sell bootleg dvds to", "sell drugs to", "buy drugs from", "swallow whole", "stretch out my anus to be able to fit", "whip", "spank", "slap", "tickle", "kiss", "make out with", "french kiss", "cook an omlette with", "slather bbq sauce all over", "viciously grate sandpaper on", "take polaroids of", "make a mix tape for", "videotape sexual acts being performed on", "melt", "stick pins in", "stab", "use my broadsword to cut", "spit on", "vomit on", "choke on", "massage", "put in dentures and bite", "survive a zombie apocalypse with", "go to disneyworld with", "google", "rape a nun with", "force a slave to touch", "meet", "lubricate", "sneak into the background of a live tv shot for the local news and show them pictures of", "slowly roast", "hire a sushi chef to make me a meal from", "feed a goat", "sell state secrets to", "climb inside", "fill goatses hole with", "eat a bowl of cereal while I cum on", "spray enema fluid from my anus all over", "wink at", "pay $30 to legally own the rights to", "fill my anus with", "slowly wrap my tight virgin asshole around", "play street hockey with", "kick", "stomp", "curbstomp", "watch a kangaroo box", "give an STD to"}

-- NOUN LIST
noun = {"cock", "dick", "dong", "penis", "schlong", "ramrod", "boner", "stiffy", "woody", "pecker", "vagina", "cunt", "pussy", "twat", "vajayjay", "anus", "ass", "asshole", "butthole", "fudge cave", "severed head", "fist", "forearm", "collection of franklin mint plates", "coin collection", "nintendo games", "xbox", "playstation", "wii", "rancid twat", "herpes sores", "distended anus", "unkempt pubic hair", "ballsack", "nutsack", "scrotum", "dead wife", "wife", "husband", "dead husbands penis", "murdered wife's cunthole", "ex-girlfriend", "only child", "wedding dress", "hambone", "crock pot", "new computer", "ipod", "beloved pet", "oldest son", "pool boy", "grandmother's skeleton", "gay porn dvd collection", "401k", "yacht", "dna evidence", "cheerleader uniform", "handguns", "silverware", "500 thread count egyptian cotton sheets", "billiards cue", "most expensive bottle of champagne", "dead mother's tombstone", "sister's cremated remains", "bowling ball", "pony", "cat", "dog", "puppy", "kitten", "squirrel", "dragon", "hired ninja guardian", "SUV", "GPS navigation system", "prototype robot", "sex slave", "biggest dildo", "shit encrusted buttplug", "used analbeads", "wife's vibrator", "speeding ticket"}

-- LOCATION/REASON LIST
location = {"in the middle of a large scale riot", "while you blow a donkey on stage in Mexico", "after just having open heart surgery and against my doctors orders", "and then do it again", "to travel back in time and stop the 9/11 hijackers", "to save the lives of 428 strangers", "because thats how I roll", "while high on crystal meth", "as I simultaneously break the world record for surviving the most shark bites", "to prove my innocence to the jury", "during my political campaign for city council", "before I die", "to prove that I'm a man", "to earn money so I can go to college", "to break into my budding career in adult film", "while wrestling a live bear", "because I think boys will like me better", "to make friends", "to distract the werewolf who is hunting me", "for my new website promotion", "at a high school football half time show", "to pay my mortgage", "in front of my wife", "as a way to protest global warming", "to prove my love to a young jewish boy", "because I promised my dead sister I would", "to prevent Skynet from developing Artificial Intelligence", "so that I can help the crash survivors of Oceanic Flight 815", "because it is my destiny", "to prove that crime does pay", "because I'm drunk and fuck you", "while scuba diving", "while riding my segway personal transporter", "instead of curing cancer", "to prove that I am the second coming of Jesus Christ", "because I love you", "to show you that I care", "while stealing from Costco", "so that I can sell the footage on ebay", "because I'm being forced at gunpoint to do so", "to single handedly cause an earthquake", "to resurrect Adolf Hitler", "so I finally have something to write about on my blog"}

function choice(list)
  return list[math.random(#list)]
end

function handofgod()
  notify.show("", string.format("I would like to %s your %s %s.", choice(verb), choice(noun), choice(location)), "", "")
end

hotkey.bind({"cmd", "alt", "ctrl"}, "H", handofgod)
